pub mod error;
pub mod generation;
pub mod metadata;
pub mod metadata_keys;
pub mod persistence;
pub mod tantivy;
pub use error::{StorageError, StorageResult};
pub use generation::{GcSummary, GenerationId, GenerationState, IndexLayout};
pub use metadata::{DataSource, EMISSION_SEMANTICS_VERSION, IndexMetadata};
pub use metadata_keys::MetadataKey;
pub use persistence::{BuildFacade, BuildMode, IndexPersistence};
pub use tantivy::{DocumentIndex, SearchResult};
